In [ ]:
import pandas as pd
import requests

In [ ]:
response =requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [ ]:
pd.DataFrame(response.json()['results'])[['id', 'title', 'release_date']]

         id                                           title release_date
0   1560520           Batman: Knightfall Part 1: Knightfall   2026-06-23
1    980431                 Avatar Aang: The Last Airbender   2026-07-24
2   1007757                                         Swapped   2026-05-01
3   1632181                             Accidental Partners   2026-03-12
4   1311031  Demon Slayer: Kimetsu no Yaiba Infinity Castle   2025-07-18
5   1621552                                 Facing El Chapo   2026-08-21
6       278                        The Shawshank Redemption   1994-09-23
7       238                                   The Godfather   1972-03-14
8    687163                               Project Hail Mary   2026-03-15
9    936075                                         Michael   2026-04-22
10  1232449                                    Young Hearts   2024-10-26
11      389                                    12 Angry Men   1957-04-10
12      240                           The Godfather Part II   1974-12-20
13      424                                Schindler's List   1993-12-15
14  1630423                             My Dearest Assassin   2026-05-06
15      155                                 The Dark Knight   2008-07-16
16  1218925              Chainsaw Man - The Movie: Reze Arc   2025-09-19
17      129                                   Spirited Away   2001-07-20
18      497                                  The Green Mile   1999-12-10
19      122   The Lord of the Rings: The Return of the King   2003-12-17

In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [30]:
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:50.0) Gecko/20100101 Firefox/50.0"}
webpage = requests.get("https://webscraper.io/test-sites/pagination", headers = headers).text

In [31]:
soup = BeautifulSoup(webpage, 'lxml')

In [32]:
print(soup.prettify)

<bound method Tag.prettify of <!DOCTYPE html>
<html lang="en">
<head>
<script src="https://app.termly.io/resource-blocker/04d89d8c-0d17-44fe-bead-65034ef2b40c"></script>
<!-- Google Tag Manager -->
<script nonce="8jiyOV9AYfz5jJPXWS5S57DZl9s3zW6v">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Test site with pagination links | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=653924ea635f75d0421534ee17c2b31b" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=ec07a6547e9f26dd0a05acf4cf8b8609" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/pagination" rel="canonical"/>
<meta content="Test site with pagination links | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/pagination" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script nonce="8jiyOV9AYfz5jJPXWS5S57DZl9s3zW6v">
		if (document.cookie.indexOf('announcement_dismissed=1') > -1) document.documentElement.classList.add('announcement-dismissed')
	</script>
<script defer="" src="/js/app.js?id=e95f7d9783f442c064c61e4f45794b47"></script>
</head>
<body class="ws-v2">
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<script nonce="8jiyOV9AYfz5jJPXWS5S57DZl9s3zW6v" type="text/javascript">
		!function (e, t, n) {
			function a() {
				var e = t.getElementsByTagName("script")[0],
					n = t.createElement("script");
				n.type = "text/javascript", n.async = !0, n.src = "https://beacon-v2.helpscout.net", e.parentNode.insertBefore(n, e)
			}

			if (e.Beacon = n = function (t, n, a) {
				e.Beacon.readyQueue.push({method: t, options: n, data: a})
			}, n.readyQueue = [], "complete" === t.readyState) return a();
			e.attachEvent ? e.attachEvent("onload", a) : e.addEventListener("load", a, !1)
		}(window, document, window.Beacon || function () {
		});
	</script>
<script nonce="8jiyOV9AYfz5jJPXWS5S57DZl9s3zW6v" type="text/javascript">
		window.Beacon('init', '1c5f94f4-1403-4003-925a-ae1a295b7d38')
	</script>
<header class="v2-header">
<div class="v2-announcement alert alert-dismissible fade show m-0" role="alert">
<div class="container text-center">
<a class="v2-announcement__link" href="https://cloud.webscraper.io/register?utm_source=cloud-landing&amp;utm_medium=announcement-bar">
<span>Web Scraper Cloud</span>
<span class="full-announcement d-none d-lg-inline">replaces your complex scraping stack.</span>
<span class="mobile-announcement d-inline d-lg-none">-</span>
<span class="v2-announcement-try">Try it free for 7 days</span>
<svg class="v2-button-icon-right" fill="none" height="18" viewbox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg">
<path d="M10 14.25L15 9L10 3.75M15 9L3 9" stroke="#00303D" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.4"></path>
</svg>
</a>
<button aria-label="Close" class="v2-announcement__close d-none d-lg-inline" data-bs-dismiss="alert" type="button">
<svg fill="none" height="18" viewbox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg">
<path d="M13.5 4.5L4.5 13.5M13.5 13.5L4.5 4.5" stroke="#00303D" stroke-linecap="round" stroke-width="1.4"></path>
</svg>
</button>
</div>
</div>
<nav aria-label="Primary" class="navbar navbar-expand-xl navbar-dark v2-navbar">
<div class="container">
<a class="navbar-brand v2-navbar__brand" href="/">
<img alt="Web Scraper" height="38" src="/img/logo-v2.svg" width="116"/>
</a>
<div class="d-flex">
<a class="v2-btn v2-btn--white d-inline d-xl-none" href="https://cloud.webscraper.io/">
					Cloud login
				</a>
<button aria-controls="v2-navbar-collapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler v2-navbar__toggler" data-bs-target="#v2-navbar-collapse" data-bs-toggle="collapse" type="button">
<svg class="closed-icon" fill="none" height="14" viewbox="0 0 18 14" width="18" xmlns="http://www.w3.org/2000/svg">
<path d="M3.75 0.75H13.75M0.75 6.75H16.75H3.75M3.75 12.75H13.75" stroke="#00D1E7" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path>
</svg>
<svg class="open-icon" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
<path d="M12.75 0.750003L0.75 12.75M12.75 12.75L0.750001 0.75" stroke="#00D1E7" stroke-linecap="round" stroke-width="1.5"></path>
</svg>
</button>
</div>
<div class="collapse navbar-collapse v2-navbar__collapse" id="v2-navbar-collapse">
<div class="mobile-menu-divider"></div>
<ul class="navbar-nav v2-navbar__nav">
<li class="nav-item">
<a class="nav-link v2-navbar__link" href="/">Web Scraper Cloud</a>
</li>
<li class="nav-item">
<a class="nav-link v2-navbar__link" href="/web-scraper-extension">Extension</a>
</li>
<li class="nav-item">
<a class="nav-link v2-navbar__link" href="/pricing" id="pricing-nav-link">Pricing</a>
</li>
<li class="nav-item">
<a class="nav-link v2-navbar__link" href="/marketplace">Marketplace</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" class="nav-link v2-navbar__link dropdown-toggle" data-bs-toggle="dropdown" id="v2-solutions-dropdown" type="button">
							Solutions
							<svg fill="none" height="16" viewbox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg">
<path d="M3 6L8.00081 10.58L13 6" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-opacity="0.7" stroke-width="1.4"></path>
</svg>
</button>
<ul aria-labelledby="v2-solutions-dropdown" class="dropdown-menu v2-dropdown-menu v2-dropdown-menu--solutions">
<li>
<a class="dropdown-item v2-dropdown-item" href="/solutions/ecommerce-web-scraping">
<svg fill="none" height="24" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
<circle cx="8" cy="21" r="1"></circle>
<circle cx="19" cy="21" r="1"></circle>
<path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"></path>
</svg>
									E-commerce
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/solutions/competitor-price-monitoring">
<svg fill="none" height="24" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
<path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z"></path>
<path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"></path>
<path d="M12 18V6"></path>
</svg>
									Competitor price monitoring
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/solutions/marketplace-data-scraping">
<svg fill="none" height="24" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
<path d="M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5"></path>
<path d="M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244"></path>
<path d="M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05"></path>
</svg>
									Marketplace data scraping
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/solutions/map-monitoring">
<svg fill="none" height="24" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path>
<path d="m9 12 2 2 4-4"></path>
</svg>
									MAP
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/solutions/market-research-web-scraping">
<svg fill="none" height="24" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
<path d="M12 16v5"></path>
<path d="M16 14.639V21"></path>
<path d="M20 10.656V21"></path>
<path d="m22 3-8.646 8.646a.5.5 0 0 1-.708 0L9.354 8.354a.5.5 0 0 0-.707 0L2 15"></path>
<path d="M4 18.463V21"></path>
<path d="M8 14.656V21"></path>
</svg>
									Market research
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/solutions/lead-generation-web-scraping">
<svg fill="none" height="24" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
<circle cx="10" cy="8" r="5"></circle>
<path d="M2 21a8 8 0 0 1 10.434-7.62"></path>
<circle cx="18" cy="18" r="3"></circle>
<path d="m22 22-1.9-1.9"></path>
</svg>
									Lead generation
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/solutions/real-estate-data-extraction">
<svg fill="none" height="24" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
<path d="M10 12h4"></path>
<path d="M10 8h4"></path>
<path d="M14 21v-3a2 2 0 0 0-4 0v3"></path>
<path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2"></path>
<path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"></path>
</svg>
									Real estate data extraction
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/solutions/web-data-for-ai-training">
<svg fill="none" height="24" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
<path d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"></path>
<path d="M9 13a4.5 4.5 0 0 0 3-4"></path>
<path d="M6.003 5.125A3 3 0 0 0 6.401 6.5"></path>
<path d="M3.477 10.896a4 4 0 0 1 .585-.396"></path>
<path d="M6 18a4 4 0 0 1-1.967-.516"></path>
<path d="M12 13h4"></path>
<path d="M12 18h6a2 2 0 0 1 2 2v1"></path>
<path d="M12 8h8"></path>
<path d="M16 8V5a2 2 0 0 1 2-2"></path>
<circle cx="16" cy="13" r=".5"></circle>
<circle cx="18" cy="3" r=".5"></circle>
<circle cx="20" cy="21" r=".5"></circle>
<circle cx="20" cy="8" r=".5"></circle>
</svg>
									Web data for AI
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/solutions/web-data-for-rag-ai-agents">
<svg fill="none" height="24" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
<path d="M12 8V4H8"></path>
<rect height="12" rx="2" width="16" x="4" y="8"></rect>
<path d="M2 14h2"></path>
<path d="M20 14h2"></path>
<path d="M15 13v2"></path>
<path d="M9 13v2"></path>
</svg>
									Web data for RAG AI agents
								</a>
</li>
</ul>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" class="nav-link v2-navbar__link dropdown-toggle" data-bs-toggle="dropdown" id="v2-learn-dropdown" type="button">
							Learn
							<svg fill="none" height="16" viewbox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg">
<path d="M3 6L8.00081 10.58L13 6" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-opacity="0.7" stroke-width="1.4"></path>
</svg>
</button>
<ul aria-labelledby="v2-learn-dropdown" class="dropdown-menu v2-dropdown-menu">
<li>
<a class="dropdown-item v2-dropdown-item" href="/documentation">
<svg fill="none" height="14" viewbox="0 0 12 14" width="12" xmlns="http://www.w3.org/2000/svg">
<path d="M7.70025 0.5V2.9C7.70025 3.34183 8.05842 3.7 8.50025 3.7H10.9003M3.30025 3.7H4.90025M3.30025 6.1H8.10025M3.30025 8.5H8.10025M9.70025 1.7C9.3442 1.38143 8.97473 1.00359 8.74148 0.758186C8.58627 0.59489 8.37183 0.5 8.14654 0.5H2.10006C1.21641 0.5 0.500068 1.21634 0.500062 2.09999L0.5 11.7C0.499994 12.5836 1.21634 13.3 2.09999 13.3L9.30002 13.3C10.1837 13.3 10.9 12.5837 10.9 11.7L10.9002 3.21855C10.9002 3.014 10.8222 2.81736 10.6802 2.67009C10.4177 2.39776 9.9793 1.94968 9.70025 1.7Z" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>
									Documentation
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/tutorials">
<svg fill="none" height="10" viewbox="0 0 14 10" width="14" xmlns="http://www.w3.org/2000/svg">
<path d="M6.57034 2.72222H4.737M9.0835 6.42448L12.1834 7.95141C12.5048 8.14701 12.842 8.03174 12.8333 7.62376L12.8116 2.22736C12.7842 1.78445 12.5228 1.66359 12.1379 1.86828L9.07476 3.26038M2 9.16667H7.57033C8.39876 9.16667 9.07033 8.50339 9.07033 7.68519L9.0835 5.78503L9.07033 1.98148C9.07033 1.16328 8.39876 0.5 7.57033 0.5H2C1.17157 0.5 0.5 1.16328 0.5 1.98148V7.68519C0.5 8.50339 1.17157 9.16667 2 9.16667Z" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-opacity="0.7"></path>
</svg>
									Video Tutorials
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="/test-sites">
<svg fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg">
<path d="M0.9 4.1H12.9M2.1 13.3C1.21634 13.3 0.5 12.5837 0.5 11.7V2.1C0.5 1.21634 1.21634 0.5 2.1 0.5H11.7C12.5837 0.5 13.3 1.21634 13.3 2.1V11.7C13.3 12.5837 12.5837 13.3 11.7 13.3H2.1Z" stroke="#F4F9FC" stroke-linecap="round" stroke-opacity="0.7"></path>
</svg>
									Test Sites
								</a>
</li>
<li>
<a class="dropdown-item v2-dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
<svg fill="none" height="13" viewbox="0 0 13 13" width="13" xmlns="http://www.w3.org/2000/svg">
<path d="M1.83322 5.83333C1.83322 2.88781 4.22083 0.5 7.16611 0.5C10.1114 0.5 12.499 2.88781 12.499 5.83333C12.499 6.60002 12.3372 7.32891 12.046 7.98775L12.5 11.1662L9.77638 10.4852C9.00481 10.9192 8.11436 11.1667 7.16611 11.1667M0.500632 9.16667C0.500632 9.64584 0.601722 10.1014 0.783736 10.5132L0.5 12.4997L2.2021 12.0741C2.68429 12.3453 3.24077 12.5 3.83337 12.5C5.67399 12.5 7.16611 11.0076 7.16611 9.16667C7.16611 7.32572 5.67399 5.83333 3.83337 5.83333C1.99275 5.83333 0.500632 7.32572 0.500632 9.16667Z" stroke="#F4F9FC" stroke-linecap="round" stroke-linejoin="round" stroke-opacity="0.7"></path>
</svg>
									Forum
								</a>
</li>
</ul>
</li>
</ul>
<div class="v2-navbar__actions">
<a class="v2-btn v2-btn--primary-700 d-none d-xl-inline-flex install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
						Install extension
					</a>
<a class="v2-btn v2-btn--white d-none d-xl-inline-flex" href="https://cloud.webscraper.io/">
						Cloud login
					</a>
</div>
</div>
</div>
</nav>
</header>
<div>
<main>
<div class="container test-sites-cars">
<div class="alert alert-warning mt-0 mb-4" role="alert">
<b>Warning!</b> This is a demo website created for web scraping practice. All listings, images, prices, and auction data are fictional and are not available for purchase.
</div>
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse light-nav">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<p class="sidebar-title">Contents</p>
<li class="nav-item active">
<a class="nav-link" href="/test-sites/pagination" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/pagination/BMW" itemprop="url">
<span itemprop="name">BMW</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/pagination/Ferrari" itemprop="url">
<span itemprop="name">Ferrari</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/pagination/Ford" itemprop="url">
<span itemprop="name">Ford</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/pagination/Jaguar" itemprop="url">
<span itemprop="name">Jaguar</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/pagination/Mercedes-Benz" itemprop="url">
<span itemprop="name">Mercedes-Benz</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/pagination/Nissan" itemprop="url">
<span itemprop="name">Nissan</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/pagination/Porsche" itemprop="url">
<span itemprop="name">Porsche</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/pagination/Toyota" itemprop="url">
<span itemprop="name">Toyota</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<div class="row test-items-container g-4 mb-3" data-current-page="1" data-last-page="17">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card sitemap-card test-sites-card" itemscope="" itemtype="https://schema.org/Product">
<div class="card-head">
<a class="card-head-url" href="https://webscraper.io/test-sites/product/mercedes-benz-w123-280e-1955-c001">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites-cars/Mercedes-Benz-W123-280E-1955-1-thumbnail.avif"/>
</a>
<div class="availability">
<div class="badge" style="background-color: #527e59;">
							Available: 1

In [35]:

for i in soup.find_all('p', class_='price col-6 mb-0 text-end p-0'):
    print(i.text.strip())

USD 228 511
USD 18 457
USD 268 210
USD 104 195
USD 277 672
USD 157 569

In [37]:
car = soup.find_all('div', class_='col-md-4 col-xl-4 col-lg-4')

In [38]:
len(car)

6

In [54]:
from pandas._config.config import describe_option
name = []
description = []
for i in car:
  name.append(i.find('h3').text.strip())
  description.append(i.find_all('p', class_='description text-muted')[0].text)

In [45]:
name

['Mercedes-Benz W123 280E 1955',
 'BMW E24 635CSi 1954',
 'Jaguar XJ6 1983',
 'Nissan 300ZX Z31 1966',
 'Ferrari F40 1984',
 'Mercedes-Benz W123 280E 1972']

In [55]:
description

['Uncompromising Stuttgart saloon',
 'Shark-nose grand tourer',
 'Silky British luxury saloon',
 'Angular Japanese sports coupe',
 'Raw Prancing Horse icon',
 'Early W123, driver condition']

In [56]:
d = {'name': name, 'description': description}

In [57]:
df = pd.DataFrame(d)

In [58]:
df

                           name                      description
0  Mercedes-Benz W123 280E 1955  Uncompromising Stuttgart saloon
1           BMW E24 635CSi 1954          Shark-nose grand tourer
2               Jaguar XJ6 1983      Silky British luxury saloon
3         Nissan 300ZX Z31 1966    Angular Japanese sports coupe
4              Ferrari F40 1984          Raw Prancing Horse icon
5  Mercedes-Benz W123 280E 1972     Early W123, driver condition

ValueError: could not convert string to float: 'Mercedes-Benz W123 280E 1955'